-- Keevan Blog — SEO Keyword Seed Data (54 keywords)
-- Generated from src/lib/seed-keywords.ts

INSERT OR IGNORE INTO Keyword (id, keyword, category, searchVolume, difficulty, usedCount) VALUES
('kw-start-01', 'how to sell ebooks online in Uganda', 'start-selling', 480, 'low', 0),
('kw-start-02', 'best platform to sell digital products in Kenya', 'start-selling', 720, 'medium', 0),
('kw-start-03', 'sell PDF guides online Tanzania', 'start-selling', 320, 'low', 0),
('kw-start-04', 'how to start selling digital downloads Rwanda', 'start-selling', 210, 'low', 0),
('kw-start-05', 'create online store for ebooks East Africa', 'start-selling', 590, 'medium', 0),
('kw-start-06', 'self publishing ebooks Uganda authors', 'start-selling', 380, 'low', 0),
('kw-start-07', 'free platform to sell digital products Africa', 'start-selling', 880, 'medium', 0),
('kw-start-08', 'upload PDF and sell online Africa', 'start-selling', 410, 'low', 0),
('kw-start-09', 'how to set up digital storefront in Kampala', 'start-selling', 170, 'low', 0),
('kw-start-10', 'sell templates online East African creators', 'start-selling', 260, 'low', 0),
('kw-start-11', 'how to price ebooks in Ugandan shillings', 'start-selling', 140, 'low', 0),
('kw-start-12', 'mobile money payments for digital products', 'start-selling', 650, 'medium', 0),

('kw-mkt-01', 'market ebooks on WhatsApp Uganda', 'marketing', 530, 'low', 0),
('kw-mkt-02', 'tiktok marketing for digital products East Africa', 'marketing', 870, 'medium', 0),
('kw-mkt-03', 'facebook ads for selling ebooks Kenya', 'marketing', 610, 'medium', 0),
('kw-mkt-04', 'instagram reels for digital creators Africa', 'marketing', 740, 'medium', 0),
('kw-mkt-05', 'how to grow whatsapp status sales Uganda', 'marketing', 410, 'low', 0),
('kw-mkt-06', 'content marketing for African authors', 'marketing', 350, 'medium', 0),
('kw-mkt-07', 'email marketing for digital product creators', 'marketing', 820, 'medium', 0),
('kw-mkt-08', 'seo for selling ebooks online Africa', 'marketing', 290, 'high', 0),
('kw-mkt-09', 'how to use x twitter to sell digital downloads', 'marketing', 220, 'medium', 0),
('kw-mkt-10', 'influencer marketing for digital products Uganda', 'marketing', 180, 'low', 0),
('kw-mkt-11', 'telegram channel for selling ebooks Kenya', 'marketing', 240, 'low', 0),

('kw-money-01', 'make money selling ebooks Uganda', 'make-money', 980, 'medium', 0),
('kw-money-02', 'passive income digital products Kenya', 'make-money', 1240, 'medium', 0),
('kw-money-03', 'how much can I earn selling ebooks Tanzania', 'make-money', 320, 'low', 0),
('kw-money-04', 'side hustle selling PDF guides Rwanda', 'make-money', 190, 'low', 0),
('kw-money-05', 'withdraw mobile money earnings from digital sales', 'make-money', 460, 'low', 0),
('kw-money-06', 'monetize writing skills East Africa', 'make-money', 540, 'medium', 0),
('kw-money-07', 'how to price digital downloads for African market', 'make-money', 370, 'medium', 0),
('kw-money-08', 'minimum withdrawal threshold digital products Africa', 'make-money', 220, 'low', 0),
('kw-money-09', 'earn 50000 UGX per day selling ebooks', 'make-money', 280, 'low', 0),
('kw-money-10', 'multiple streams of income as a creator Africa', 'make-money', 410, 'medium', 0),
('kw-money-11', 'how to bundle digital products for higher sales', 'make-money', 320, 'medium', 0),

('kw-tools-01', 'free tools to create ebooks Africa', 'tools', 760, 'low', 0),
('kw-tools-02', 'best AI tools for African content creators', 'tools', 1480, 'high', 0),
('kw-tools-03', 'canva alternatives for ebook design Uganda', 'tools', 230, 'low', 0),
('kw-tools-04', 'how to convert word to PDF for free', 'tools', 1620, 'low', 0),
('kw-tools-05', 'compress PDF file under 4MB for upload', 'tools', 590, 'low', 0),
('kw-tools-06', 'free ebook cover design tools online', 'tools', 880, 'medium', 0),
('kw-tools-07', 'notion templates for content creators', 'tools', 1240, 'medium', 0),
('kw-tools-08', 'google docs to ebook workflow', 'tools', 320, 'low', 0),
('kw-tools-09', 'AI writing tools for African authors', 'tools', 1090, 'high', 0),
('kw-tools-10', 'best apps for selling digital downloads', 'tools', 720, 'medium', 0),
('kw-tools-11', 'payment gateway comparison East Africa', 'tools', 410, 'medium', 0),
('kw-tools-12', 'free image hosting for ebook covers', 'tools', 180, 'low', 0),

('kw-stories-01', 'Ugandan author making money online 2025', 'success-stories', 290, 'low', 0),
('kw-stories-02', 'Kenyan creator selling digital products case study', 'success-stories', 410, 'medium', 0),
('kw-stories-03', 'Tanzanian educator earning from ebooks', 'success-stories', 170, 'low', 0),
('kw-stories-04', 'Rwanda digital creator success story', 'success-stories', 130, 'low', 0),
('kw-stories-05', 'first 1000 dollars selling digital products Africa', 'success-stories', 380, 'medium', 0),
('kw-stories-06', 'how a teacher in Kampala sells study guides online', 'success-stories', 220, 'low', 0),
('kw-stories-07', 'from side hustle to full time digital creator East Africa', 'success-stories', 340, 'medium', 0),
('kw-stories-08', 'ebook that sold 500 copies in Uganda', 'success-stories', 180, 'low', 0);
